version: "3.8"
services:
  # PHP service
  app:
    build: ./.Docker
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - app-network
    ports:
      - "9003:9003"  # Xdebug port

  # MySQL database service

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
#    volumes:
#      - mysql-data:/var/lib/mysql
    networks:
      - app-network



  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:cached
      - ./.Docker/nginx/:/etc/nginx/conf.d/
      - ./.Docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network

    #php myadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    #    restart: always
      UPLOAD_LIMIT: 300M
    ports:
      - 8081:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

#volumes:
#  mysql-data:
